# Generated by Django 5.1 on 2024-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0005_dashboard_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='outcome_text',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=models.CharField(max_length=150),
        ),
    ]
