# Generated by Django 5.1 on 2024-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0006_alter_project_outcome_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='company',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
