# Generated by Django 5.1 on 2024-09-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0007_dashboard_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='Q0', max_length=5),
        ),
    ]
