# Generated by Django 5.1 on 2024-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0011_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
