# Generated by Django 5.1 on 2024-09-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0012_respondent_password_alter_respondent_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
