# Generated by Django 5.1 on 2024-09-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0016_alter_comment_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Q1',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q10',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q4',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q5',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q6',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q7',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q8',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='Q9',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='email',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESG.question'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='company',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='first_name',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='last_name',
            field=models.CharField(default='Null', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
