# Generated by Django 5.1 on 2024-09-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0018_remove_question_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='email',
            field=models.EmailField(default='Null', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area_header',
            name='areaheader',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='company',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
