# Generated by Django 5.1 on 2024-09-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0023_answer_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='respondent',
        ),
    ]
