# Generated by Django 5.1 on 2024-09-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0024_rename_name_comment_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
