# Generated by Django 5.1 on 2024-09-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0031_surveys_area_context_area_divcontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='opacity',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
    ]
