# Generated by Django 5.1 on 2024-09-30 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0035_rename_divcontext_surveys_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESG.surveys'),
        ),
    ]
