# Generated by Django 5.1 on 2024-09-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0037_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
    ]
