# Generated by Django 5.1 on 2024-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0039_outcome_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='opacity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
