# Generated by Django 5.1 on 2024-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0042_alter_outcome_colors_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(max_length=300),
        ),
    ]
