# Generated by Django 5.1 on 2024-12-08 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0047_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_topic',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ESG.surveys'),
        ),
    ]
