# Generated by Django 5.1 on 2024-12-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0049_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='Intro',
            field=models.CharField(max_length=2000),
        ),
    ]
