# Generated by Django 5.1 on 2025-02-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0063_final_result_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis_Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.CharField(blank=True, max_length=3000)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
    ]
