# Generated by Django 5.1 on 2025-02-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESG', '0065_remove_question_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
