# Generated by Django 5.1 on 2024-09-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0003_topic_area_alter_topic_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_header',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISO22301.area'),
        ),
    ]
