# Generated by Django 5.1 on 2024-09-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0008_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default='Q', max_length=5),
        ),
    ]
