# Generated by Django 5.1 on 2024-09-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0010_rename_value_answer_q1_answer_q10_answer_q2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name', max_length=30, null=True)),
                ('last_name', models.CharField(default='Last Name', max_length=30, null=True)),
                ('company', models.CharField(default='Company', max_length=30, null=True)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
    ]
