# Generated by Django 5.1 on 2024-09-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0014_alter_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='respondent',
        ),
    ]
