# Generated by Django 5.1 on 2024-09-03 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0015_rename_question_answer_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ISO22301.area'),
        ),
    ]
