# Generated by Django 5.1 on 2024-09-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0017_rename_q1_answer_value_remove_answer_q10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
