# Generated by Django 5.1 on 2024-09-10 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0019_respondent_email_alter_area_header_areaheader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISO22301.area'),
        ),
    ]
