# Generated by Django 5.1 on 2024-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0020_question_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areatext',
            field=models.CharField(default='Null', max_length=400),
            preserve_default=False,
        ),
    ]
