# Generated by Django 5.1 on 2024-09-11 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0022_area_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISO22301.area'),
        ),
    ]
