# Generated by Django 5.1 on 2024-09-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0026_comment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='respondent',
            field=models.IntegerField(null=True),
        ),
    ]
