# Generated by Django 5.0.7 on 2024-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0027_alter_answer_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='area_topic',
            name='context',
            field=models.CharField(default='item_', max_length=400),
            preserve_default=False,
        ),
    ]
