# Generated by Django 5.0.7 on 2024-09-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0028_area_topic_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='area_topic',
            name='divcontext',
            field=models.CharField(default='null', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
