# Generated by Django 5.0.7 on 2024-09-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0029_answer_timestamp_area_topic_divcontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column_header',
            name='colcount',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
