# Generated by Django 5.1 on 2024-09-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0030_column_header_colcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=200)),
                ('context', models.CharField(max_length=400)),
                ('divcontext', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='context',
            field=models.CharField(default='item_', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='divcontext',
            field=models.CharField(default='div.item_', max_length=400),
            preserve_default=False,
        ),
    ]
