# Generated by Django 5.1 on 2024-09-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0032_surveys_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='taken',
            field=models.IntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
    ]
