# Generated by Django 5.1 on 2024-09-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0033_surveys_taken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Respondent',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='respondent',
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
