# Generated by Django 5.1 on 2024-09-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0034_delete_respondent_remove_answer_respondent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveys',
            old_name='divcontext',
            new_name='color',
        ),
    ]
