# Generated by Django 5.1 on 2024-09-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0036_area_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
