# Generated by Django 5.1 on 2024-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0040_alter_surveys_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome_colors',
            name='opacity',
            field=models.DecimalField(blank=True, decimal_places=1, default='0.5', max_digits=2),
            preserve_default=False,
        ),
    ]
