# Generated by Django 5.1 on 2024-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0041_outcome_colors_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome_colors',
            name='opacity',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
