# Generated by Django 5.1 on 2024-12-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0046_project_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ISO22301.surveys'),
        ),
    ]
