# Generated by Django 5.1 on 2025-01-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0057_respondent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='company',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='respondent',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
