# Generated by Django 5.1 on 2025-02-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISO22301', '0064_analysis_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
